export const CONFIG_RELATIVE_TIME_DEFAULT = {
  future: "in %s",
  past: "%s ago",
  s: "a few seconds",
  ss: "%d seconds",
  m: "a minute",
  mm: "%d minutes",
  h: "an hour",
  hh: "%d hours",
  d: "a day",
  dd: "%d days",
  w: "a week",
  ww: "%d weeks",
  M: "a month",
  MM: "%d months",
  y: "a year",
  yy: "%d years",
}

export const CONFIG_RELATIVE_TIME_SHORT = {
  future: "in %s",
  past: "%s",
  s: "1m",
  ss: "%ss",
  m: "1m",
  mm: "%dm",
  h: "1h",
  hh: "%dh",
  d: "a day",
  dd: "%dd",
  M: "a month",
  MM: "%dM",
  y: "a year",
  yy: "%dY",
}
